### PR TITLE
sfputilbase.py: fix the Python crash upon IO failures

### PR DESCRIPTION
**Pull request by ds952811**
This fixes the following failure:

Nov 18 00:57:55.488171 sonic INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Nov 18 00:57:55.488171 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 683, in <module>
Nov 18 00:57:55.488171 sonic INFO pmon#supervisord: xcvrd     sys.exit(main())
Nov 18 00:57:55.488171 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 606, in main
Nov 18 00:57:55.488188 sonic INFO pmon#supervisord: xcvrd     rc = post_port_sfp_info_to_db(logical_port, int_tbl)
Nov 18 00:57:55.488188 sonic INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 265, in post_port_sfp_info_to_db
Nov 18 00:57:55.488206 sonic INFO pmon#supervisord: xcvrd     port_info_dict = platform_sfputil.get_transceiver_info_dict(physical_port)
Nov 18 00:57:55.488206 sonic INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/sonic_platform_base/sonic_sfp/sfputilbase.py", line 726, in get_transceiver_info_dict
Nov 18 00:57:55.501232 sonic INFO pmon#supervisord: xcvrd     sfp_vendor_pn_raw = self._read_eeprom_specific_bytes(sysfsfile_eeprom, (offset + OSFP_VENDOR_PN_OFFSET), XCVR_VENDOR_PN_WIDTH)
Nov 18 00:57:55.501232 sonic INFO pmon#supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/sonic_platform_base/sonic_sfp/sfputilbase.py", line 314, in _read_eeprom_specific_bytes
Nov 18 00:57:55.501390 sonic INFO pmon#supervisord: xcvrd     print("Error: reading sysfs file %s" % sysfs_sfp_i2c_client_eeprom_path)
Nov 18 00:57:55.501390 sonic INFO pmon#supervisord: xcvrd NameError: global name 'sysfs_sfp_i2c_client_eeprom_path' is not defined

Signed-off-by: Dante Su <dante.su@broadcom.com>

### CODE REVIEW

**Review by zhenggen-xu — COMMENTED** [review]
The fix looked good.  However, in what cases we hit the IOError?

**Comment by ds952811** [comment]
This defect is identified by multiple attempts of QSFPDD module reinsertion, and since the I2C performance of Silverstone is pretty slow, it's quite easy to recreate this failure.

**Comment by zhenggen-xu** [comment]
> This defect is identified by multiple attempts of QSFPDD module reinsertion, and since the I2C performance of Silverstone is pretty slow, it's quite easy to recreate this failure.

If I am not mistaken,  xcvrd will retry max 5 times with 1 second interval if hit this IOError.  So with the fix in this PR and retry logic, things are working, right?

**Comment by ds952811** [comment]
Yes, with the fix in this PR, the xcvrd will not crash due to the undefined symbol, and successfully resume after the IO failures.

**Review by zhenggen-xu — APPROVED** [review]

**Pull request merged**
